config/routes.rb
Rails.application.routes.draw do
  resources :business_profiles do 
    member do 
      get :join 
      delete :leave 
  end
end
  resources :profiles
  devise_for :users, :controllers => { :registrations => "registrations" }
  get 'admin', to: 'admin#index'

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role: admin
        can :manage, :all
    elsif user.has_role? :resident
        can :manage, :events
        can :manage, :messages
        can :manage, :profiles
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/business_profile.rb
class BusinessProfile < ActiveRecord::Base
	has_many :business_users 
	has_many :users, through: :business_users

extend FriendlyId
friendly_id :name, use: :slugged
end

app/models/business_user.rb
class BusinessUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :business_profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

	mount_uploader :profile_pic, ProfilePicUploader

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :profile
	has_many :business_users 
	has_many :business_profiles, through: :business_users
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 after_create :assign_resident_role, :create_profile
 
 def assign_resident_role
 self.add_role :resident
  end	

  def create_profile
  	self.profile = Profile.create!
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	unless current_user.has_role? :admin
  		redirect_to root_path, :alert => "Access denied."
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/business_profiles_controller.rb
class BusinessProfilesController < ApplicationController
  before_action :set_business_profile, only: [:join, :leave, :show, :edit, :update, :destroy]
  def join 
    @business_profile.users << current_user
    redirect_to :back
  end

  def leave 
    @business_profile.users.delete(current_user)
    redirect_to :back
  end

  # GET /business_profiles
  # GET /business_profiles.json
  def index
    @business_profiles = BusinessProfile.all
  end

  # GET /business_profiles/1
  # GET /business_profiles/1.json
  def show
    @users = @business_profile.users
  end

  # GET /business_profiles/new
  def new
    @business_profile = BusinessProfile.new
  end

  # GET /business_profiles/1/edit
  def edit
  end

  # POST /business_profiles
  # POST /business_profiles.json
  def create
    @business_profile = BusinessProfile.new(business_profile_params)
    @business_profile.users << current_user
    
    respond_to do |format|
      if @business_profile.save
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully created.' }
        format.json { render :show, status: :created, location: @business_profile }
      else
        format.html { render :new }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_profiles/1
  # PATCH/PUT /business_profiles/1.json
  def update
    @business_profile.slug = nil
    respond_to do |format|
      if @business_profile.update(business_profile_params)
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_profile }
      else
        format.html { render :edit }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_profiles/1
  # DELETE /business_profiles/1.json
  def destroy
    @business_profile.destroy
    respond_to do |format|
      format.html { redirect_to business_profiles_url, notice: 'Business profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_profile
      @business_profile = BusinessProfile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_profile_params
      params.require(:business_profile).permit(:name, :logo, :description, :head_count, :website_link)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @business_profiles = @profile.user.business_profiles

  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @profile = current_user.profile
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    @profile = current_user.profile
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :name, :profile_pic, :bio, :phone)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def after_sign_up_path_for(resource)
  	edit_profile_path(resource.profile)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_profiles_helper.rb
module BusinessProfilesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/business_profiles/_form.html.erb
<%= simple_form_for(@business_profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :logo %>
    <%= f.input :description %>
    <%= f.input :head_count %>
    <%= f.input :website_link %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/business_profiles/edit.html.erb
<h1>Editing Business Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_profile %> |
<%= link_to 'Back', business_profiles_path %>

app/views/business_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Business Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th>Description</th>
      <th>Head count</th>
      <th>Website link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_profiles.each do |business_profile| %>
      <tr>
        <td><%= business_profile.name %></td>
        <td><%= business_profile.logo %></td>
        <td><%= business_profile.description %></td>
        <td><%= business_profile.head_count %></td>
        <td><%= business_profile.website_link %></td>
        <td><%= link_to 'Show', business_profile %></td>
        <td><%= link_to 'Edit', edit_business_profile_path(business_profile) %></td>
        <td><%= link_to 'Destroy', business_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business profile', new_business_profile_path %>

app/views/business_profiles/new.html.erb
<h1>New Business Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', business_profiles_path %>

app/views/business_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @business_profile.name %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @business_profile.logo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @business_profile.description %>
</p>

<p>
  <strong>Head count:</strong>
  <%= @business_profile.users.count %>
</p>

<p>
  <strong>Website link:</strong>
  <%= @business_profile.website_link %>
</p>
<h3>People in this business</h3>
<% @users.each do |user| %>
<p><%= user.profile.name %></p>
<% end %>

<% if @business_profile.users.include?(current_user) %>
  <%= link_to "I don't work here", leave_business_profile_path, method: :delete, class: 'btn btn-danger' %>
  <% else %>
  <%= link_to 'I work here', join_business_profile_path, class: 'btn btn-success' %>

<% end %>

<%= link_to 'Edit', edit_business_profile_path(@business_profile) %> |
<%= link_to 'Back', business_profiles_path %>

app/views/home/index.html.erb
<%= content_for :title, 'Testing' %>

<h1>Aura Creative</h1>
<h3>COWORKING & EVENT SPACE</h3>

<%= image_tag 'elephant.jpg', alt: 'This is a picture of an elephant', title: 'This is an elephant', class: 'img-thumbnail img-circle' %>

<a href="<%= asset_path 'elephant.jpg' %>"></a>

<% if user_signed_in? %>
	<p>Your email address is <%= current_user.email %></p>
	<% if current_user.profile %>
	<p>Welcome <%= current_user.profile.name %></p>
	<% else %>
	<%= link_to "Create your profile", new_profile_path, class: 'btn btn-primary' %>
	<% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Aura Creative</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Resident businesses', business_profiles_path %></li>
        <% unless user_signed_in? %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if current_user.profile %>
            <%= current_user.profile.name %>

            <% else %>
            Menu 
            <% end %>

            <%#current_user.profile ? current_user.profile.name : 'Menu' %>
            <%# current_user.profile.name if current_user.profile%>

            <span class="caret"></span></a>
            <ul class="dropdown-menu">
            <% if current_user.has_role? :admin %>
              <li><a href="/admin">Admin</a></li>
              <% end %>
              <% if current_user.profile %>
              <li><%= link_to "My Profile", profile_path(current_user.profile) %></li>
              <% else %>
              <li><%= link_to "Create Profile", new_profile_path %></li>
              <% end %>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auracreative</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Aura Creative' %></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    
    <%= f.input :name %>
    <%= f.input :profile_pic %>
    <%= f.input :bio %>
    <%= f.input :phone %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Profile pic</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user %></td>
        <td><%= profile.name %></td>
        <td><%= profile.profile_pic %></td>
        <td><%= profile.bio %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @profile.user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Profile pic:</strong>
  <%= image_tag(@profile.profile_pic_url(:thumbnail)) %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<p>
<strong>Phone:</strong> 
<%= @profile.phone %>
</p>


<% if current_user.profile == @profile %>
<%= link_to 'Edit my profile', edit_profile_path(@profile), class: 'btn btn-warning' %> 
<% end %>

<%= link_to 'Create your business profile', new_business_profile_path %>

<br>

<h2>I work here:</h2>

<ul>
<% @business_profiles.each do |business_profile| %>
<li><%= business_profile.name %></li>
<% link_to business_profile.name, business_profile_path(business_profile) %></ul>

<% end %>

</ul>